import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import { Providers } from "./providers"; // Providers import
import { Session } from "inspector/promises";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Link from 'next/link';
import Nav from '@/components/Nav';



const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);
  
  return (
    <html lang="kr" data-theme="light" className={`${pretendard.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta name="color-scheme" content="light only"/>
        <meta name="supported-color-schemes" content="light"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejumyeongjo.css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/jejugothic.css"/>
      </head>

      <body data-theme="light"
        className={`${pretendard.className} font-sans antialiased`}
      >
    <Providers session={session}>
              <Nav/>
              {children}
        </Providers>
      </body>
    </html>
  );
}
